# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filters_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filterDialog(object):
    def setupUi(self, filterDialog):
        filterDialog.setObjectName("filterDialog")
        filterDialog.resize(925, 397)
        self.tabs = QtWidgets.QTabWidget(filterDialog)
        self.tabs.setGeometry(QtCore.QRect(20, 10, 331, 361))
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.slider1 = QtWidgets.QSlider(self.tab)
        self.slider1.setGeometry(QtCore.QRect(130, 40, 31, 221))
        self.slider1.setMinimum(1)
        self.slider1.setMaximum(31)
        self.slider1.setSingleStep(1)
        self.slider1.setTracking(True)
        self.slider1.setOrientation(QtCore.Qt.Vertical)
        self.slider1.setObjectName("slider1")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(110, 270, 71, 21))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.slider1_counter = QtWidgets.QLabel(self.tab)
        self.slider1_counter.setGeometry(QtCore.QRect(140, 10, 31, 31))
        self.slider1_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider1_counter.setObjectName("slider1_counter")
        self.dx_checkBox = QtWidgets.QCheckBox(self.tab)
        self.dx_checkBox.setGeometry(QtCore.QRect(30, 110, 81, 20))
        self.dx_checkBox.setChecked(True)
        self.dx_checkBox.setObjectName("dx_checkBox")
        self.dy_checkBox = QtWidgets.QCheckBox(self.tab)
        self.dy_checkBox.setGeometry(QtCore.QRect(30, 150, 81, 20))
        self.dy_checkBox.setObjectName("dy_checkBox")
        self.apply_button = QtWidgets.QPushButton(self.tab)
        self.apply_button.setEnabled(True)
        self.apply_button.setGeometry(QtCore.QRect(210, 290, 93, 28))
        self.apply_button.setObjectName("apply_button")
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(110, 270, 71, 21))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.slider2_counter = QtWidgets.QLabel(self.tab_2)
        self.slider2_counter.setGeometry(QtCore.QRect(140, 10, 31, 31))
        self.slider2_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider2_counter.setObjectName("slider2_counter")
        self.slider2 = QtWidgets.QSlider(self.tab_2)
        self.slider2.setGeometry(QtCore.QRect(130, 40, 31, 221))
        self.slider2.setMinimum(1)
        self.slider2.setMaximum(31)
        self.slider2.setSingleStep(1)
        self.slider2.setOrientation(QtCore.Qt.Vertical)
        self.slider2.setObjectName("slider2")
        self.apply_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.apply_button_2.setEnabled(True)
        self.apply_button_2.setGeometry(QtCore.QRect(210, 290, 93, 28))
        self.apply_button_2.setObjectName("apply_button_2")
        self.tabs.addTab(self.tab_2, "")
        self.image_label = QtWidgets.QLabel(filterDialog)
        self.image_label.setGeometry(QtCore.QRect(360, 30, 550, 340))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_label.setText("")
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")

        self.retranslateUi(filterDialog)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(filterDialog)

    def retranslateUi(self, filterDialog):
        _translate = QtCore.QCoreApplication.translate
        filterDialog.setWindowTitle(_translate("filterDialog", "Filters"))
        self.tabs.setWhatsThis(_translate("filterDialog", "<html><head/><body><p>this is tab1</p><p><br/></p></body></html>"))
        self.label.setText(_translate("filterDialog", "Kernel Size"))
        self.slider1_counter.setText(_translate("filterDialog", "0"))
        self.dx_checkBox.setText(_translate("filterDialog", "Dx"))
        self.dy_checkBox.setText(_translate("filterDialog", "Dy"))
        self.apply_button.setText(_translate("filterDialog", "Apply Filter"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("filterDialog", "Sobel Filter"))
        self.label_2.setText(_translate("filterDialog", "Kernel Size"))
        self.slider2_counter.setText(_translate("filterDialog", "0"))
        self.apply_button_2.setText(_translate("filterDialog", "Apply Filter"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("filterDialog", "Laplace Filter"))

    def getComponents(self):
        return [self.tabs,
                self.slider1, self.slider2,
                self.slider1_counter, self.slider2_counter,
                self.dx_checkBox, self.dy_checkBox,
                self.apply_button, self.apply_button_2]


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    filterDialog = QtWidgets.QDialog()
    ui = Ui_filterDialog()
    ui.setupUi(filterDialog)
    filterDialog.show()
    sys.exit(app.exec_())
