# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'noiseRemove_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_noiseRemoveDialog(object):
    def setupUi(self, noiseRemoveDialog):
        noiseRemoveDialog.setObjectName("noiseRemoveDialog")
        noiseRemoveDialog.resize(1141, 461)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(noiseRemoveDialog.sizePolicy().hasHeightForWidth())
        noiseRemoveDialog.setSizePolicy(sizePolicy)
        noiseRemoveDialog.setMinimumSize(QtCore.QSize(1141, 461))
        noiseRemoveDialog.setMaximumSize(QtCore.QSize(1141, 461))
        noiseRemoveDialog.setToolTip("")
        self.frame = QtWidgets.QFrame(noiseRemoveDialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1121, 51))
        self.frame.setStyleSheet("QFrame#frame{\n"
"border-radius: 4px;\n"
"border: 2px solid rgb(229, 229, 229);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 401, 41))
        self.label_10.setStyleSheet("color: #FFF;\n"
"font: 75 20pt \"Berlin Sans FB Demi\";")
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setObjectName("label_10")
        self.close_button = QtWidgets.QPushButton(self.frame)
        self.close_button.setGeometry(QtCore.QRect(1090, 20, 17, 17))
        self.close_button.setMinimumSize(QtCore.QSize(16, 16))
        self.close_button.setMaximumSize(QtCore.QSize(17, 17))
        self.close_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.minimize_button = QtWidgets.QPushButton(self.frame)
        self.minimize_button.setGeometry(QtCore.QRect(1060, 20, 17, 17))
        self.minimize_button.setMinimumSize(QtCore.QSize(16, 16))
        self.minimize_button.setMaximumSize(QtCore.QSize(17, 17))
        self.minimize_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.minimize_button.setText("")
        self.minimize_button.setObjectName("minimize_button")
        self.frame_2 = QtWidgets.QFrame(noiseRemoveDialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 70, 1121, 381))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"border-radius: 4px;\n"
"border: 2px solid rgb(229, 229, 229);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.image_label = QtWidgets.QLabel(self.frame_2)
        self.image_label.setGeometry(QtCore.QRect(560, 30, 550, 340))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_label.setText("")
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.tabs = QtWidgets.QTabWidget(self.frame_2)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 541, 361))
        self.tabs.setWhatsThis("")
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.slider2_counter = QtWidgets.QLabel(self.tab)
        self.slider2_counter.setGeometry(QtCore.QRect(340, 20, 31, 31))
        self.slider2_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider2_counter.setObjectName("slider2_counter")
        self.slider2 = QtWidgets.QSlider(self.tab)
        self.slider2.setGeometry(QtCore.QRect(330, 50, 31, 221))
        self.slider2.setMinimum(0)
        self.slider2.setMaximum(100)
        self.slider2.setSingleStep(1)
        self.slider2.setProperty("value", 0)
        self.slider2.setTracking(True)
        self.slider2.setOrientation(QtCore.Qt.Vertical)
        self.slider2.setObjectName("slider2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(310, 280, 81, 21))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.slider1_counter = QtWidgets.QLabel(self.tab)
        self.slider1_counter.setGeometry(QtCore.QRect(120, 20, 31, 31))
        self.slider1_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider1_counter.setObjectName("slider1_counter")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(90, 280, 81, 21))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.apply_button = QtWidgets.QPushButton(self.tab)
        self.apply_button.setEnabled(True)
        self.apply_button.setGeometry(QtCore.QRect(420, 290, 93, 28))
        self.apply_button.setObjectName("apply_button")
        self.slider1 = QtWidgets.QSlider(self.tab)
        self.slider1.setGeometry(QtCore.QRect(110, 50, 31, 221))
        self.slider1.setMinimum(0)
        self.slider1.setMaximum(100)
        self.slider1.setSingleStep(1)
        self.slider1.setProperty("value", 0)
        self.slider1.setTracking(True)
        self.slider1.setOrientation(QtCore.Qt.Vertical)
        self.slider1.setObjectName("slider1")
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(220, 280, 71, 21))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.slider3 = QtWidgets.QSlider(self.tab_2)
        self.slider3.setGeometry(QtCore.QRect(240, 50, 31, 221))
        self.slider3.setMinimum(0)
        self.slider3.setMaximum(100)
        self.slider3.setSingleStep(1)
        self.slider3.setOrientation(QtCore.Qt.Vertical)
        self.slider3.setObjectName("slider3")
        self.apply_button_1 = QtWidgets.QPushButton(self.tab_2)
        self.apply_button_1.setEnabled(True)
        self.apply_button_1.setGeometry(QtCore.QRect(420, 290, 93, 28))
        self.apply_button_1.setObjectName("apply_button_1")
        self.slider3_counter = QtWidgets.QLabel(self.tab_2)
        self.slider3_counter.setGeometry(QtCore.QRect(250, 20, 31, 31))
        self.slider3_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider3_counter.setObjectName("slider3_counter")
        self.tabs.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_7 = QtWidgets.QLabel(self.tab_6)
        self.label_7.setGeometry(QtCore.QRect(80, 280, 81, 21))
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setObjectName("label_7")
        self.slider5 = QtWidgets.QSlider(self.tab_6)
        self.slider5.setGeometry(QtCore.QRect(200, 50, 31, 221))
        self.slider5.setMinimum(0)
        self.slider5.setMaximum(1000)
        self.slider5.setSingleStep(1)
        self.slider5.setProperty("value", 0)
        self.slider5.setTracking(True)
        self.slider5.setOrientation(QtCore.Qt.Vertical)
        self.slider5.setObjectName("slider5")
        self.slider5_counter = QtWidgets.QLabel(self.tab_6)
        self.slider5_counter.setGeometry(QtCore.QRect(210, 20, 31, 31))
        self.slider5_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider5_counter.setObjectName("slider5_counter")
        self.slider4 = QtWidgets.QSlider(self.tab_6)
        self.slider4.setGeometry(QtCore.QRect(100, 50, 31, 221))
        self.slider4.setMinimum(0)
        self.slider4.setMaximum(100)
        self.slider4.setSingleStep(1)
        self.slider4.setProperty("value", 0)
        self.slider4.setTracking(True)
        self.slider4.setOrientation(QtCore.Qt.Vertical)
        self.slider4.setObjectName("slider4")
        self.slider4_counter = QtWidgets.QLabel(self.tab_6)
        self.slider4_counter.setGeometry(QtCore.QRect(110, 20, 31, 31))
        self.slider4_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider4_counter.setObjectName("slider4_counter")
        self.apply_button_2 = QtWidgets.QPushButton(self.tab_6)
        self.apply_button_2.setEnabled(True)
        self.apply_button_2.setGeometry(QtCore.QRect(420, 290, 93, 28))
        self.apply_button_2.setObjectName("apply_button_2")
        self.label_8 = QtWidgets.QLabel(self.tab_6)
        self.label_8.setGeometry(QtCore.QRect(190, 280, 51, 21))
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.slider6_counter = QtWidgets.QLabel(self.tab_6)
        self.slider6_counter.setGeometry(QtCore.QRect(300, 20, 31, 31))
        self.slider6_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider6_counter.setObjectName("slider6_counter")
        self.label_9 = QtWidgets.QLabel(self.tab_6)
        self.label_9.setGeometry(QtCore.QRect(280, 280, 51, 21))
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setObjectName("label_9")
        self.slider6 = QtWidgets.QSlider(self.tab_6)
        self.slider6.setGeometry(QtCore.QRect(290, 50, 31, 221))
        self.slider6.setMinimum(0)
        self.slider6.setMaximum(1000)
        self.slider6.setSingleStep(1)
        self.slider6.setProperty("value", 0)
        self.slider6.setTracking(True)
        self.slider6.setOrientation(QtCore.Qt.Vertical)
        self.slider6.setObjectName("slider6")
        self.tabs.addTab(self.tab_6, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(210, 280, 81, 21))
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.slider7_counter = QtWidgets.QLabel(self.tab_3)
        self.slider7_counter.setGeometry(QtCore.QRect(220, 20, 31, 31))
        self.slider7_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider7_counter.setObjectName("slider7_counter")
        self.slider7 = QtWidgets.QSlider(self.tab_3)
        self.slider7.setGeometry(QtCore.QRect(210, 50, 31, 221))
        self.slider7.setMinimum(0)
        self.slider7.setMaximum(50)
        self.slider7.setSingleStep(1)
        self.slider7.setProperty("value", 0)
        self.slider7.setTracking(True)
        self.slider7.setOrientation(QtCore.Qt.Vertical)
        self.slider7.setObjectName("slider7")
        self.apply_button_3 = QtWidgets.QPushButton(self.tab_3)
        self.apply_button_3.setEnabled(True)
        self.apply_button_3.setGeometry(QtCore.QRect(420, 290, 93, 28))
        self.apply_button_3.setObjectName("apply_button_3")
        self.tabs.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.apply_button_4 = QtWidgets.QPushButton(self.tab_5)
        self.apply_button_4.setEnabled(True)
        self.apply_button_4.setGeometry(QtCore.QRect(420, 290, 93, 28))
        self.apply_button_4.setObjectName("apply_button_4")
        self.slider8_counter = QtWidgets.QLabel(self.tab_5)
        self.slider8_counter.setGeometry(QtCore.QRect(220, 20, 31, 31))
        self.slider8_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider8_counter.setObjectName("slider8_counter")
        self.slider8 = QtWidgets.QSlider(self.tab_5)
        self.slider8.setGeometry(QtCore.QRect(210, 50, 31, 221))
        self.slider8.setMinimum(0)
        self.slider8.setMaximum(100)
        self.slider8.setSingleStep(1)
        self.slider8.setProperty("value", 0)
        self.slider8.setTracking(True)
        self.slider8.setOrientation(QtCore.Qt.Vertical)
        self.slider8.setObjectName("slider8")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(210, 280, 81, 21))
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.tabs.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(40, 30, 101, 16))
        self.label.setObjectName("label")
        self.label_point1MaskFilter = QtWidgets.QLabel(self.tab_4)
        self.label_point1MaskFilter.setGeometry(QtCore.QRect(120, 70, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_point1MaskFilter.sizePolicy().hasHeightForWidth())
        self.label_point1MaskFilter.setSizePolicy(sizePolicy)
        self.label_point1MaskFilter.setObjectName("label_point1MaskFilter")
        self.label_point2MaskFilter = QtWidgets.QLabel(self.tab_4)
        self.label_point2MaskFilter.setGeometry(QtCore.QRect(120, 110, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_point2MaskFilter.sizePolicy().hasHeightForWidth())
        self.label_point2MaskFilter.setSizePolicy(sizePolicy)
        self.label_point2MaskFilter.setObjectName("label_point2MaskFilter")
        self.pushButton_reset = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_reset.setGeometry(QtCore.QRect(170, 290, 75, 23))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.apply_button_5 = QtWidgets.QPushButton(self.tab_4)
        self.apply_button_5.setEnabled(False)
        self.apply_button_5.setGeometry(QtCore.QRect(380, 290, 75, 23))
        self.apply_button_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.apply_button_5.setCheckable(False)
        self.apply_button_5.setAutoDefault(True)
        self.apply_button_5.setDefault(False)
        self.apply_button_5.setFlat(False)
        self.apply_button_5.setObjectName("apply_button_5")
        self.pushButton_preview = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_preview.setEnabled(False)
        self.pushButton_preview.setGeometry(QtCore.QRect(270, 290, 75, 23))
        self.pushButton_preview.setObjectName("pushButton_preview")
        self.tabs.addTab(self.tab_4, "")

        self.retranslateUi(noiseRemoveDialog)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(noiseRemoveDialog)

    def retranslateUi(self, noiseRemoveDialog):
        _translate = QtCore.QCoreApplication.translate
        noiseRemoveDialog.setWindowTitle(_translate("noiseRemoveDialog", "Remove Noise"))
        self.label_10.setText(_translate("noiseRemoveDialog", "Remove Noise"))
        self.slider2_counter.setText(_translate("noiseRemoveDialog", "0"))
        self.label_3.setText(_translate("noiseRemoveDialog", "Kernel Width"))
        self.slider1_counter.setText(_translate("noiseRemoveDialog", "0"))
        self.label_4.setText(_translate("noiseRemoveDialog", "Kernel Height"))
        self.apply_button.setText(_translate("noiseRemoveDialog", "Apply Filter"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("noiseRemoveDialog", "Average Filter"))
        self.label_2.setText(_translate("noiseRemoveDialog", "Kernel Size"))
        self.apply_button_1.setText(_translate("noiseRemoveDialog", "Apply Filter"))
        self.slider3_counter.setText(_translate("noiseRemoveDialog", "0"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("noiseRemoveDialog", "Median Filter"))
        self.label_7.setText(_translate("noiseRemoveDialog", "Kernel Size"))
        self.slider5_counter.setText(_translate("noiseRemoveDialog", "0"))
        self.slider4_counter.setText(_translate("noiseRemoveDialog", "0"))
        self.apply_button_2.setText(_translate("noiseRemoveDialog", "Apply Filter"))
        self.label_8.setText(_translate("noiseRemoveDialog", "Sigma X"))
        self.slider6_counter.setText(_translate("noiseRemoveDialog", "0"))
        self.label_9.setText(_translate("noiseRemoveDialog", "Sigma Y"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_6), _translate("noiseRemoveDialog", "Gaussian Blur"))
        self.label_5.setText(_translate("noiseRemoveDialog", "Offset"))
        self.slider7_counter.setText(_translate("noiseRemoveDialog", "0"))
        self.apply_button_3.setText(_translate("noiseRemoveDialog", "Apply Filter"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _translate("noiseRemoveDialog", "Notch Filter"))
        self.apply_button_4.setText(_translate("noiseRemoveDialog", "Apply Filter"))
        self.slider8_counter.setText(_translate("noiseRemoveDialog", "0"))
        self.label_6.setText(_translate("noiseRemoveDialog", "Offset"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_5), _translate("noiseRemoveDialog", "Band Filter"))
        self.label.setText(_translate("noiseRemoveDialog", "Choose Points:"))
        self.label_point1MaskFilter.setText(_translate("noiseRemoveDialog", "point_1: ?"))
        self.label_point2MaskFilter.setText(_translate("noiseRemoveDialog", "point_2: ?"))
        self.pushButton_reset.setText(_translate("noiseRemoveDialog", "Reset"))
        self.apply_button_5.setText(_translate("noiseRemoveDialog", "Apply"))
        self.pushButton_preview.setText(_translate("noiseRemoveDialog", "Preview"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), _translate("noiseRemoveDialog", "Mask Filter"))

    def getComponents(self):
            return [self.tabs,
                self.slider1, self.slider2, self.slider3, self.slider4, self.slider5, self.slider6, self.slider7, self.slider8,
                self.slider1_counter, self.slider2_counter, self.slider3_counter, self.slider4_counter, self.slider5_counter, self.slider6_counter, self.slider7_counter, self.slider8_counter,
                self.apply_button, self.apply_button_1, self.apply_button_2, self.apply_button_3, self.apply_button_4, self.apply_button_5]