# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'noiseAdd_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_noiseAddDialog(object):
    def setupUi(self, noiseAddDialog):
        noiseAddDialog.setObjectName("noiseAddDialog")
        noiseAddDialog.resize(1129, 397)
        self.tabs = QtWidgets.QTabWidget(noiseAddDialog)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 541, 361))
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabs.addTab(self.tab_3, "")
        self.filteredImage_label = QtWidgets.QLabel(noiseAddDialog)
        self.filteredImage_label.setGeometry(QtCore.QRect(560, 30, 550, 340))
        self.filteredImage_label.setFrameShape(QtWidgets.QFrame.Box)
        self.filteredImage_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.filteredImage_label.setText("")
        self.filteredImage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.filteredImage_label.setObjectName("filteredImage_label")

        self.retranslateUi(noiseAddDialog)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(noiseAddDialog)

    def retranslateUi(self, noiseAddDialog):
        _translate = QtCore.QCoreApplication.translate
        noiseAddDialog.setWindowTitle(_translate("noiseAddDialog", "Add Noise"))
        self.tabs.setWhatsThis(_translate("noiseAddDialog", "<html><head/><body><p>this is tab1</p><p><br/></p></body></html>"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("noiseAddDialog", "Salt and Pepper"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("noiseAddDialog", "Gaussian"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _translate("noiseAddDialog", "Periodic"))
